a=input("Enter the 1st string:")
print("First character:",a[0])
print("Last character:",a[-1])
b=input("Enter the 2nd string:")
print("First character:",b[0])
print("Last character:",b[-1])
c=input("Enter the 3rd string:")
print("First character:",c[0])
print("Last character:",c[-1])